export const loadStore = {
    width: 1080,
    height: 1080,
    fonts: [],
    pages: [
        {
            id: "qnL8VjyM0y",
            children: [
                {
                    id: "3zkQOzc1y1",
                    type: "image",
                    name: "",
                    opacity: 1,
                    animations: [],
                    visible: true,
                    selectable: true,
                    removable: true,
                    alwaysOnTop: false,
                    showInExport: true,
                    x: 340,
                    y: 290,
                    width: 400,
                    height: 500,
                    rotation: 0,
                    blurEnabled: false,
                    blurRadius: 10,
                    brightnessEnabled: false,
                    brightness: 0,
                    sepiaEnabled: false,
                    grayscaleEnabled: false,
                    shadowEnabled: false,
                    shadowBlur: 5,
                    shadowOffsetX: 0,
                    shadowOffsetY: 0,
                    shadowColor: "black",
                    shadowOpacity: 1,
                    draggable: true,
                    resizable: true,
                    contentEditable: true,
                    styleEditable: true,
                    src: "https://images.unsplash.com/photo-1661956602116-aa6865609028?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTY5OTZ8MXwxfGFsbHwxfHx8fHx8Mnx8MTY3ODExMzExMg&ixlib=rb-4.0.3&q=80&w=1080",
                    cropX: 0,
                    cropY: 0,
                    cropWidth: 1,
                    cropHeight: 1,
                    cornerRadius: 0,
                    flipX: false,
                    flipY: false,
                    clipSrc: "",
                    borderColor: "black",
                    borderSize: 0,
                    keepRatio: false
                },
                {
                    id: "MryBa_LlhL",
                    type: "line",
                    name: "",
                    opacity: 1,
                    animations: [],
                    visible: true,
                    selectable: true,
                    removable: true,
                    alwaysOnTop: false,
                    showInExport: true,
                    x: 360,
                    y: 531.5,
                    width: 360,
                    height: 17,
                    rotation: 0,
                    blurEnabled: false,
                    blurRadius: 10,
                    brightnessEnabled: false,
                    brightness: 0,
                    sepiaEnabled: false,
                    grayscaleEnabled: false,
                    shadowEnabled: false,
                    shadowBlur: 5,
                    shadowOffsetX: 0,
                    shadowOffsetY: 0,
                    shadowColor: "black",
                    shadowOpacity: 1,
                    draggable: true,
                    resizable: true,
                    contentEditable: true,
                    styleEditable: true,
                    color: "black",
                    dash: [4, 1],
                    startHead: "bar",
                    endHead: "circle"
                },
                {
                    id: "K6LSqcBPJi",
                    type: "svg",
                    name: "",
                    opacity: 0.64,
                    animations: [],
                    visible: true,
                    selectable: true,
                    removable: true,
                    alwaysOnTop: false,
                    showInExport: true,
                    x: 270.0192061459667,
                    y: 162.84891165172854,
                    width: 150,
                    height: 150,
                    rotation: 0,
                    blurEnabled: false,
                    blurRadius: 10,
                    brightnessEnabled: false,
                    brightness: 0,
                    sepiaEnabled: false,
                    grayscaleEnabled: false,
                    shadowEnabled: true,
                    shadowBlur: 19,
                    shadowOffsetX: -50,
                    shadowOffsetY: 24,
                    shadowColor: "rgba(255,0,0,1)",
                    shadowOpacity: 0.3399999999999999,
                    draggable: true,
                    resizable: true,
                    contentEditable: true,
                    styleEditable: true,
                    src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iMzAiIGZpbGw9InJnYigwLCAxNjEsIDI1NSkiIC8+PC9zdmc+",
                    maskSrc: "",
                    cropX: 0,
                    cropY: 0,
                    cropWidth: 1,
                    cropHeight: 1,
                    keepRatio: false,
                    flipX: false,
                    flipY: false,
                    borderColor: "black",
                    borderSize: 0,
                    cornerRadius: 0,
                    colorsReplace: {
                        "rgb(0, 161, 255)": "rgba(92,92,92,1)"
                    }
                },
                {
                    id: "mw__DsrP6v",
                    type: "svg",
                    name: "",
                    opacity: 1,
                    animations: [],
                    visible: true,
                    selectable: true,
                    removable: true,
                    alwaysOnTop: false,
                    showInExport: true,
                    x: 592.2215108834828,
                    y: 182.20870678617155,
                    width: 150,
                    height: 150,
                    rotation: 0,
                    blurEnabled: false,
                    blurRadius: 10,
                    brightnessEnabled: false,
                    brightness: 0,
                    sepiaEnabled: false,
                    grayscaleEnabled: false,
                    shadowEnabled: false,
                    shadowBlur: 5,
                    shadowOffsetX: 0,
                    shadowOffsetY: 0,
                    shadowColor: "black",
                    shadowOpacity: 1,
                    draggable: true,
                    resizable: true,
                    contentEditable: true,
                    styleEditable: true,
                    src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCA2MCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiBmaWxsPSJyZ2IoMCwgMTYxLCAyNTUpIiAvPjwvc3ZnPg==",
                    maskSrc: "",
                    cropX: 0,
                    cropY: 0,
                    cropWidth: 1,
                    cropHeight: 1,
                    keepRatio: false,
                    flipX: false,
                    flipY: false,
                    borderColor: "black",
                    borderSize: 0,
                    cornerRadius: 0,
                    colorsReplace: {}
                }
            ],
            width: "auto",
            height: "auto",
            background: "white",
            bleed: 0
        }
    ],
    unit: "px",
    dpi: 72
};

export const getImage = (url: string) => {
    return {
        id: "JLVAa-lkXW",
        type: "image",
        name: "",
        opacity: 1,
        animations: [],
        visible: true,
        selectable: true,
        removable: true,
        alwaysOnTop: false,
        showInExport: true,
        x: 214.85532181357718,
        y: 120.10244818254051,
        width: 400,
        height: 600,
        rotation: 0,
        blurEnabled: false,
        blurRadius: 10,
        brightnessEnabled: false,
        brightness: 0,
        sepiaEnabled: false,
        grayscaleEnabled: false,
        shadowEnabled: false,
        shadowBlur: 5,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowColor: "black",
        shadowOpacity: 1,
        draggable: true,
        resizable: true,
        contentEditable: true,
        styleEditable: true,
        src: url,
        cropX: 0,
        cropY: 0,
        cropWidth: 1,
        cropHeight: 1,
        cornerRadius: 0,
        flipX: false,
        flipY: false,
        clipSrc: "",
        borderColor: "black",
        borderSize: 0,
        keepRatio: false
    };
};

export const getSvg = () => {
    return {
        type: "svg",
        src: "https://upload.wikimedia.org/wikipedia/commons/3/30/Vector-based_example.svg",
        maskSrc: "", // should we draw mask image over svg element?
        keepRatio: false, // can we change aspect ratio of svg?
        x: 0,
        y: 0,
        rotation: 0,
        locked: false, // deprecated
        blurEnabled: false,
        blurRadius: 10,
        brightnessEnabled: false,
        brightness: 0,
        shadowEnabled: false,
        shadowBlur: 5,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowColor: "black",
        shadowOpacity: 1,
        width: 100,
        height: 100,
        flipX: false,
        flipY: false,
        cornerRadius: 0,
        // can user select element?
        // if false, element will be "invisible" for user clicks
        selectable: true,
        // use for absolute positing of element
        alwaysOnTop: false,
        // also we can hide some elements from the export
        showInExport: true,
        // can element be moved and rotated
        draggable: true,
        // can we change content of element?
        contentEditable: true,
        // can we remove element from UI with button or keyboard?
        removable: true,
        // can we resize element?
        resizable: true,
        // map of originalColor -> newColor, used to replace colors in svg image
        // do not change it manually. Instead use `el.replaceColor(originalColor, newColor)
        colorsReplace: {}
    };
};
